### ISSUE TITLE
Compilation script

### ISSUE THREAD

**Issue by addaleax** [huston007/angular-gettext-cli#4]
Hi! I’m working on a project where we decided to replace grunt with a set of npm/cli scripts – would you accept a PR adding support for the compiler feature of angular-gettext (as opposed to extract)? If so, would you rather have that to be a completely new script in bin/, or would you want something differentiated by a flag (e.g. `--compile`)?

/cc @nhaesler

**Comment by huston007** [comment]
@addaleax Hello!
Could you please explain how are you going to use compiled translations?
Are you going to provide .po files as source and get json as a result or something like that?

**Comment by addaleax** [comment]
Yes, exactly. Something along the lines of the `nggettext_compile` grunt task, if you have happened to look at it; You provide an input .po file, and get js or json as the output.

**Comment by huston007** [comment]
Okay, I would happily accept such PR!  You can look into [angular-gettext-loader](https://github.com/princed/angular-gettext-loader) as example.
`--compile` argument should be just enough
